version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: app/Dockerfile
    container_name: backend
    env_file:
      - ./.env
    environment:
      POSTGRES_DSN: ${POSTGRES_DSN}
      QDRANT_URL: ${QDRANT_URL}
      QDRANT_API_KEY: ${QDRANT_API_KEY}
      QDRANT_COLLECTION_NAME: ${QDRANT_COLLECTION_NAME}
      EMBEDDING_SERVICE_URL: ${EMBEDDING_SERVICE_URL}
    depends_on:
      - embedding_service
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - app-network
    environment:
      VITE_API_BASE_URL: http://backend:8000

  embedding_service:
    build:
      context: ./embedding_service
      dockerfile: Dockerfile
    container_name: embedding_service
    ports:
      - "8100:8100"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
